### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xodamcm** [David-pm-pl/VanillaEC#1]
PocketMine-MP Crash Dump Sat Apr 30 11:24:57 UTC 2022

PocketMine-MP version: 4.3.1 [Protocol 503]
Git commit: f7dce4af8802ce28a8286e1c8002af19cf986c62
PHP version: 8.0.17
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: VanillaEC

Error: foreach() argument must be of type array|object, bool given
File: plugins/VanillaEC_dev-3.phar/src/DavidGlitch04/VanillaEC/Main
Line: 134
Type: ErrorException
Backtrace:
#0 plugins/VanillaEC_dev-3.phar/src/DavidGlitch04/VanillaEC/Main(134): pocketmine\errorhandler\ErrorToExceptionHandler::handle(integer 2, string[59] foreach() argument must be of type array|object, bool given, string[88] phar:///home/container/plugins/VanillaEC_dev-3.phar/src/DavidGlitch04/VanillaEC/, integer 134)
#1 pmsrc/src/event/RegisteredListener(75): DavidGlitch04\VanillaEC\Main->onDamage(object pocketmine\event\entity\EntityDamageByEntityEvent#280532)
#2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent#280532)
#3 pmsrc/src/entity/Entity(530): pocketmine\event\Event->call()
#4 pmsrc/src/entity/Living(517): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#280532)
#5 pmsrc/src/player/Player(1733): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#280532)
#6 pmsrc/src/network/mcpe/handler/InGamePacketHandler(516): pocketmine\player\Player->attackEntity(object Largage\Largage3D\entity\Largage#372830)
#7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(306): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemOnEntityTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemOnEntityTransactionData#345290)
#8 plugins/VanillaX_v3.0.0/src/CLADevs/VanillaX/network/InGamePacketHandlerX(205): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#214517)
#9 pmsrc/vendor/pocketmine/bedrock-protocol/src/InventoryTransactionPacket(105): CLADevs\VanillaX\network\InGamePacketHandlerX->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#214517)
#10 pmsrc/src/network/mcpe/NetworkSession(398): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object CLADevs\VanillaX\network\InGamePacketHandlerX#249914)
#11 pmsrc/src/network/mcpe/NetworkSession(361): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#214517, string[228] .....!....................Damage.......PiggyCEItemVersion.......RepairCost......)
#12 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[260] c.a...."....>lu={...A..QF................"..'.r.......vp22.20.f..........%171=.()
#13 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 1, string[269] ...`....>...A..D.Kp.D....w.....P.A.z..>.....Z..,M...........%...d..x.6.....'...[)
#14 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#102739)
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#17 pmsrc/src/Server(1661): pocketmine\snooze\SleeperHandler->sleepUntil(double 1651317897.2967)
#18 pmsrc/src/Server(1047): pocketmine\Server->tickProcessor()
#19 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#20 pmsrc/src/PocketMine(327): pocketmine\server()
#21 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[125] 			if($item->hasEnchantment(EnchantmentIdMap::getInstance()->fromId($ench->getMcpeId()))){
[126] 				if(in_array($player::getNetworkTypeId(), self::ARTHROPODS)){
[127] 					$event->setBaseDamage($event->getBaseDamage() + (2.5 * $item->getEnchantmentLevel(EnchantmentIdMap::getInstance()->fromId($ench->getMcpeId()))));
[128] 				}
[129] 			}
[130] 			 $en = new LootingEnchantment();
[131] 			 if(($level = $damager->getInventory()->getItemInHand()->getEnchantmentLevel(EnchantmentIdMap::getInstance()->fromId($en->getMcpeId()))) > 0){
[132] 			 	if($player instanceof Player == false and $player instanceof Living and $event->getFinalDamage() >= $player->getHealth()){
[133] 			 		$add = mt_rand(0, $level + 1);
[134] 			 		foreach($this->getConfig()->get("looting.entities") as $eid => $items){
[135] 			 			$id = constant(Entity::class."::".strtoupper($eid));
[136] 						
[137] 			 			if($player::getNetworkTypeId() == $id){
[138] 			 				$drops = $this->getLootingDrops($player->getDrops(), $items, $add);
[139] 			 				foreach($drops as $drop){
[140] 			 				    $damager->getWorld()->dropItem($player->getPosition()->asVector3(), $drop);
[141] 			 				}
[142] 							
[143] 			 				$player->flagForDespawn();
[144] 			 			}

**Comment by 0xliam627** [comment]
Fixed https://github.com/Taylor-pm-pl/VanillaEC/commit/c9da407e73831551fb528c695d5118be020a36ef
